#    dave_interfaces/srv/DriveDistance.srv
# Request
# distance to drive (meters), positive or negative
float32 distance
# positive speed m/s
float32 speed
---
# Result
# status: goal reached: 0, stall occurred: 1, time expired: 2
int8 status
